version: "3.9"
name: trello
services:
  postgres:
    image: postgres:16.0-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: "trello"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"