CREATE TABLE boards
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(32),
    description TEXT,
    created_at  TIMESTAMP(6),
    updated_at  TIMESTAMP(6)
);

CREATE TABLE cards
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    board_id    BIGINT REFERENCES boards (id) ON DELETE CASCADE ,
    name        VARCHAR(32),
    description TEXT,
    created_at  TIMESTAMP(6),
    updated_at  TIMESTAMP(6)
);